board/urls.py
from django.urls import path
from board.views import index, about, contacts, add_post, post_list_in_table, post_list, post_detail, post_edit, \
    post_delete

app_name = 'board'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('post/add', add_post, name='add_post'),
    path('post/table/', post_list_in_table, name='post_list_in_table'),
    path('post/', post_list, name='post_list'),
    path('posts/<slug:slug>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', post_edit, name='post_edit'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
]

my_board/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import root
from my_board import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "board.views.forbidden"
handler404 = "board.views.page_not_found"
handler500 = "board.views.server_error"

users/urls.py
from django.urls import path
from .views import register, log_in, log_out, user_detail, change_password, user_edit

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
    path('user/<int:pk>/edit/', user_edit, name='user_edit'),
]

board/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# from django.utils.text import slugify

User = get_user_model()


class Post(models.Model):
    # поля таблицы
    # author = models.CharField(max_length=50, verbose_name='Автор')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(max_length=500, verbose_name='Текст объявления')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Опубликовано',
                                      editable=False)  # Параметр 'editable' отключает возможность для редактирования
    url_adders = models.CharField(max_length=150, verbose_name='Ссылка на сайт')
    image = models.ImageField(upload_to='posts/', null=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('board:post_detail', kwargs={'slug': self.slug})

    class Meta:  # Настроечный класс
        # Имя таблицы в единственном числе
        verbose_name = 'Объявление'
        # Имя таблицы
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return self.title

board/forms.py
from django import forms
from .models import Post


# class PostForm(forms.Form):
#     author = forms.CharField(max_length=50, label='Автор')
#     title = forms.CharField(max_length=200, label='Заголовок')
#     text = forms.CharField(label='Текст объявления', widget=forms.Textarea)

# второй способ создания форм более простой
class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        author = kwargs.pop('author', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if author:
            self.fields['author'].initial = author
            self.fields['author'].disabled = True

        self.fields['author'].widget.attrs['placeholder'] = 'Укажите автора'
        self.fields['title'].widget.attrs['placeholder'] = 'Укажите заголовок'
        self.fields['text'].widget.attrs['placeholder'] = 'Текст объявления'
        self.fields['image'].widget.attrs['placeholder'] = 'Фотография'
        self.fields['url_adders'].widget.attrs['placeholder'] = 'Укажите email'

    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'image', 'url_adders']  # так правильнее всего
        # второй способ не надо так делать
        # fields = '__all__'
        # exclude = ['created_at'] или так

    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #
    #     self.fields['author'].widget.attrs['placeholder'] = 'Укажите автора'
    #     self.fields['title'].widget.attrs['placeholder'] = 'Укажите заголовок'
    #     self.fields['text'].widget.attrs['placeholder'] = 'Текст объявления'
    #     self.fields['image'].widget.attrs['placeholder'] = 'Фотография'
    #     self.fields['url_adders'].widget.attrs['placeholder'] = 'Укажите email'

# class DeleteNewForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = []

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Post


# Create your views here.
def root(request):
    posts = Post.objects.all()
    context = {
        'title': 'Объявления',
        'posts': posts
    }
    return render(request, template_name='board/index.html', context=context)


def index(request):
    posts = Post.objects.all()
    context = {
        'title': 'Объявления',
        'posts': posts
    }
    return render(request, template_name='board/index.html', context=context)


def about(request):
    context = {
        'name': 'Ivan',
        'lastname': 'Ivanov',
        'email': 'ivanivanov@yandex.ru',

    }
    return render(request, template_name='board/about.html', context=context)


def contacts(request):
    context = {
        'name': 'Тестовый сайт на Django',
        'email': 'd.test@yandex.ru',
        'title': 'Здесь будут контакты'
    }
    return render(request, template_name='board/contacts.html', context=context)


@login_required
def add_post(request):
    if request.method == 'GET':
        form = PostForm(author=request.user)
        context = {
            'form': form,
            'title': 'Добавление объявления'
        }
        return render(request, template_name='board/add_post.html', context=context)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, author=request.user)
        if form.is_valid():
            # post = Post()
            # post.author = form.cleaned_data['author']
            # post.title = form.cleaned_data['title']
            # post.text = form.cleaned_data['text']
            # post.image = form.cleaned_data['image']
            # post.save()
            form.save(commit=True)

        return index(request)


def post_list_in_table(request):  # Посты в виде таблицы
    # Получаем все объекты модели Post
    posts = Post.objects.all()
    context = {
        'title': 'Посты',
        'posts': posts
    }
    return render(request, template_name='board/posts_in_table.html', context=context)


def post_list(request):
    # Получаем все объекты модели Post
    # сортируем по убыванию
    posts = Post.objects.all().order_by('-created_at')
    # показываем по 4 поста на странице
    # получаем номер страницы из url
    paginator = Paginator(posts, 4)
    page_number = request.GET.get('page')
    # получаем объекты для текущей страницы
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Объявления',
        'page_obj': page_obj
    }
    return render(request, template_name='board/posts.html', context=context)


def post_detail(request, slug):
    # получаем объект с заданным первичным ключом
    posts = get_object_or_404(Post, slug=slug)
    # post = Post.objects.get(pk=pk)
    context = {
        'title': 'Информация о посте',
        'posts': posts
    }

    return render(request, template_name='board/post_detail.html', context=context)


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)  # получить объект по ключу
    if request.method == 'POST':
        form = PostForm(data=request.POST, instance=post, author=request.user)
        if form.is_valid():
            form.save()
            return post_list(request)

    else:
        form = PostForm(instance=post, author=request.user)
    context = {
            'form': form,
            'title': 'Редактировать объявление'
        }
    return render(request, template_name='board/post_edit.html', context=context)


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)  # получить объект по ключу
    if request.method == 'POST':
        post.delete()
        return redirect('board:post_list')
    return render(request, template_name="board/post_delete.html", context={'post': post})


def forbidden(request, exception):
    return render(request, template_name='board/403.html', status=403)


def page_not_found(request, exception):
    return render(request, template_name='board/404.html', status=404)


def server_error(request):
    return render(request, template_name='board/500.html', status=500)

board/templates/board/about.html
{% extends 'board/base.html' %}

{% block content %}
<link  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
         integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<style>
    .style-2 {
    list-style-type: "\1F7E2";
    }
    .style-1 {
    list-style-type: "\01f449";
    }
    html, body {
    background-color: #75b798;
    }
</style>
<ul>
<li class="style-1"><h2>Это страница о нас</h2></li>
    <hr>
<br>
    <ul>
    <li class="style-2"><h3>Автор - <i>{{name}} {{lastname}}</i></h3></li>
    <li class="style-2"><h3>Электронный адрес - <i>{{email}}</i></h3></li>
    </ul>
</ul>
<br>
<a href="{% url 'board:index'%}"><h4>На главную страницу</h4></a>
{% endblock content %}

board/templates/board/add_post.html
{% extends 'board/base.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

<h2 style="text-align: center;">Добавить новое объявление</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Создать объявление</button>
</form>

<a href="{% url 'board:index'%}"><h3>На главную страницу</h3></a>
{% endblock content %}

board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="icon" href="{% static 'favicon/approval-icon.ico' %}"/>


</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'board:index' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'board:post_list' %}">Посты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:add_post' %}">Создать новый пост</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Аккаунт
                    </a>
                    <ul class="dropdown-menu">
                        {% if not user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username }}</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                <li hidden class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/index.html
{% extends 'board/base.html' %}
{% load static %}
{% block content %}

<!--<style>-->
<!--    body {-->
<!--    height: 20%;-->
<!--    background : linear-gradient(to right, #00ffd0, #c0faff);-->
<!--}-->
<!--</style>-->
<!--<h2>Это главная страница</h2>-->
<!--<div class="main">-->
<!--    <a href="{% url 'board:post_list' %}"><h3>1. Все посты</h3></a>-->
<!--    <a href="{% url 'board:post_list_in_table' %}"><h3>2. Посты в виде таблицы</h3></a>-->
<!--    <a href="{% url 'board:add_post' %}"><h3>3. Создать новый пост</h3></a>-->
<!--    <a href="{% url 'board:about' %}"><h3>4. О сайте</h3></a>-->
<!--    <a href="{% url 'board:contacts' %}"><h3>5. Контакты</h3></a>-->
<!--</div>-->

<style>
    body {
    background-color: beige!important;
}
a {
    color: green!important;
}
p {
    font-style: italic!important;
}
img {
    width: 200px;
}
h2 {
    text-decoration: underline;
}
</style>
<!--<div class="container my-5">-->

<!--    <div class="row gy-5">-->
<!--        <p></p>-->
<!--        {% for post in posts %}-->
<!--        <div class="col-6 bg-white text-dark text-center">-->
<!-- <h3 class="text-center  my-3">Автор {{post.author}}: <a href="{{ post.get_absolute_url }}">-->


<!--            <div class="text-center">-->
<!--                <img width="150px" height="100px" src="/media/{{post.image}}" class="rounded" alt="#">-->
<!--            </div>-->

<!--                {{post.title}}</a></p></h4>-->
<!--            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-images"-->
<!--                 viewBox="0 0 16 16">-->
<!--                <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/>-->
<!--                <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2M14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1M2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1z"/>-->
<!--            </svg>-->
<!--            <p>{{post.text}}</p>-->

<!--            <button type="button" class="btn btn-primary"><i class="bi bi-images"></i> Edit</button>-->
<!--            <button type="button" class="btn btn-danger"><i class="bi bi-x-octagon-fill"></i> Delete</button>-->

<!--            <hr>-->
<!-- {% endfor %}-->
<!--        </div>-->

<!--    </div>-->
<!--</div>-->
<div class="container">
    <div class="row gy-5">
        <p></p>
        {% for post in posts %}
        <div class="col-6 bg-light text-dark text-center">
             <h4 class="text-uppercase">Объявление №{{post.id}}</h4>
            <h4 class="text-center  my-3">Автор {{post.author}}: <a href="{{ post.get_absolute_url }}">
                <i>{{post.title}}</i></a></h4>
            <div class="text-center">
                {% if post.image %}
                        <img width="200px" height="150px" src="{{post.image.url}}">
                {% endif %}
<!--                <img width="200px" height="150px" src="/media/{{post.image}}">-->
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-images my-3"
                 viewBox="0 0 16 16">
                <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/>
                <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2M14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1M2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1z"/>
            </svg>
            <p>{{post.text}}</p>

            <p>Дата создания поста: <i>{{post.created_at}}</i></p>
            <a href="{{post.url_adders}}">Подробнее...</a>
            <hr>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

board/templates/board/index_copy.html
{% extends 'board/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/header.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css">
<style>
    body {
        background-image: url("{% static 'img/priroda-66.jpg' %}");
        /*background-image: url( "/static/img/priroda-66.jpg");*/
        background-repeat: repeat;
        max-width: 1600px;
    }
</style>


<header>
    <div class="logo">
        <a href="#"><img src="{% static 'img/K_3.jpg' %}" alt="Logo"></a>
    </div>
    <nav>
        <ul>
            <li><a href="{% url 'board:post_list_in_table'%}">Объявления в виде таблицы</a></li>
            <li><a href="{% url 'board:post_list'%}">Все объявления</a></li>
            <li><a href="{% url 'board:add_post'%}">Создать новое объявление</a></li>
            <li><a href="{% url 'board:about'%}">О сайте</a></li>
            <li><a href="{% url 'board:contacts'%}">Контакты</a></li>
            <li><a href="#">Регистрация</a></li>
        </ul>
    </nav>
</header>
<div class="one">
    <main>
        {% for post in posts %}
        <section class="container Row">
            <article class="col-md-12">
                <div class="row">
                    <div class="col-md-12 col-sm-4 image">
                        {% if post.image %}
                        <img src="{{post.image.url}}">
                        {% endif %}
                    </div>
                    <div class="col-md-12 col-sm-4">
                        <h4 class="text-uppercase">Объявление №{{post.id}}</h4>
                        <br>
                        <p>Автор: {{post.author}}: <a href="{% url 'board:post_detail' pk=post.id %}">
                            Редактировать: {{post.title}}</a></p>
                        <br>
                        <p>{{post.text}}</p>
                        <p>{{post.created_at}}</p>
                        <p>Сайт: <i>{{post.url_adders}}</i></p>
                        <a href="{{post.url_adders}}">Подробнее...</a>
                        <br>
                    </div>
                </div>
            </article>
        </section>
        {% endfor %}
    </main>
</div>
<footer>
    <div class="social">
        <p>Follow me on social media</p>
        <ul class="wrapper">
            <a href="https://vk.com/">
                <li class="icon linkedin">
                    <span class="tooltip">VK</span>
                    <span><i class="fab fa-vk"></i></span>
                </li>
            </a>
            <a href="https://www.youtube.com/">
                <li class="icon youtube">
                    <span class="tooltip">YouTube</span>
                    <span><i class="fab fa-youtube"></i></span>
                </li>
            </a>
            <a href="https://github.com/">
                <li class="icon github">
                    <span class="tooltip">GitHub</span>
                    <span><i class="fab fa-github"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon facebook">
                    <span class="tooltip">Facebook</span>
                    <span><i class="fab fa-facebook-f"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon instagram">
                    <span class="tooltip">Instagram</span>
                    <span><i class="fab fa-instagram"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon twitter">
                    <span class="tooltip">Twitter</span>
                    <span><i class="fab fa-twitter"></i></span>
                </li>
            </a>
            <a href="https://codepen.io/trending">
                <li class="icon github">
                    <span class="tooltip">CodePen</span>
                    <span><i class="fab fa-codepen"></i></span>
                </li>
            </a>
        </ul>
    </div>
    <div class="final_text"></div>
    <p>Copyright &copy; All rights reserved</p>
</footer>

<script src="{% static 'javaScript/header.js' %}"></script>

</html>
{% endblock content %}

board/templates/board/index_new.html
{% extends 'board/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/header.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css">
<style>
    body {
        background-image: url("{% static 'img/priroda-66.jpg' %}");
        /*background-image: url( "/static/img/priroda-66.jpg");*/
        background-repeat: repeat;
        max-width: 1600px;
    }
</style>


<header>
    <div class="logo">
        <a href="#"><img src="{% static 'img/K_3.jpg' %}" alt="Logo"></a>
    </div>
    <nav>
        <ul>
            <li><a href="{% url 'board:post_list_in_table'%}">Объявления в виде таблицы</a></li>
            <li><a href="{% url 'board:post_list'%}">Все объявления</a></li>
            <li><a href="{% url 'board:add_post'%}">Создать новое объявление</a></li>
            <li><a href="{% url 'board:about'%}">О сайте</a></li>
            <li><a href="{% url 'board:contacts'%}">Контакты</a></li>
            <li><a href="{% url 'users:register' %}">Регистрация</a></li>
       </ul>
    </nav>
</header>
<div class="one">
    <main>
        {% for post in posts %}
        <section class="container Row">
            <article class="col-md-12">
                <div class="row">
                    <div class="col-md-12 col-sm-4 image">
                        {% if post.image %}
                        <img src="{{post.image.url}}">
                        {% endif %}
                    </div>
                    <div class="col-md-12 col-sm-4">
                        <h4 class="text-uppercase">Объявление №{{post.id}}</h4>
                        <br>
                        <p>Автор: {{post.author}}: <a href="{% url 'board:post_detail' pk=post.id %}">
                            Редактировать: {{post.title}}</a></p>
                        <br>
                        <p>{{post.text}}</p>
                        <p>{{post.created_at}}</p>
                        <p>Сайт: <i>{{post.url_adders}}</i></p>
                        <a href="{{post.url_adders}}">Подробнее...</a>
                        <br>
                    </div>
                </div>
            </article>
        </section>
        {% endfor %}
    </main>
</div>
<footer>
    <div class="social">
        <p>Follow me on social media</p>
        <ul class="wrapper">
            <a href="https://vk.com/">
                <li class="icon linkedin">
                    <span class="tooltip">VK</span>
                    <span><i class="fab fa-vk"></i></span>
                </li>
            </a>
            <a href="https://www.youtube.com/">
                <li class="icon youtube">
                    <span class="tooltip">YouTube</span>
                    <span><i class="fab fa-youtube"></i></span>
                </li>
            </a>
            <a href="https://github.com/">
                <li class="icon github">
                    <span class="tooltip">GitHub</span>
                    <span><i class="fab fa-github"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon facebook">
                    <span class="tooltip">Facebook</span>
                    <span><i class="fab fa-facebook-f"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon instagram">
                    <span class="tooltip">Instagram</span>
                    <span><i class="fab fa-instagram"></i></span>
                </li>
            </a>
            <a href="#">
                <li class="icon twitter">
                    <span class="tooltip">Twitter</span>
                    <span><i class="fab fa-twitter"></i></span>
                </li>
            </a>
            <a href="https://codepen.io/trending">
                <li class="icon github">
                    <span class="tooltip">CodePen</span>
                    <span><i class="fab fa-codepen"></i></span>
                </li>
            </a>
        </ul>
    </div>
    <div class="final_text"></div>
    <p>Copyright &copy; All rights reserved</p>
</footer>

<script src="{% static 'javaScript/header.js' %}"></script>

</html>
{% endblock content %}

board/templates/board/post_confirm_delete.html
{% extends 'board/base.html' %}

{% block content %}
<h2>Delete Post</h2>

<form method="POST">
  {% csrf_token %}
  <p>Are you sure that you want to delete the post "{{post.title}}"?</p>
  <div>
    <button type="submit">Yes, Delete</button>
    <a href="{% url 'board:index' %}">Cancel</a>
  </div>
</form>

{% endblock content %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}
{% block content %}

<style>
  i {
  color: green;
  }
</style>
<br>
<div class="container">
<h2><i>Информация об объявлении № {{posts.id}}</i></h2>
<p>Автор - <i>{{posts.author}}</i></p>
  <p>Название - <i>{{posts.title}}</i>></p>
<p>Текст объявления:</p>
<p>{{posts.text}}</p>

{% if posts.image %}
    <img width="300px" height="200px" src="{{posts.image.url}}">
{% endif %}
<br>
  <p>Создан: <i>{{posts.created_at}}</i>></p>
<div>
    <a href="{% url 'board:post_edit' pk=posts.id%}" class="btn btn-primary">Редактировать</a>
    <form action="{% url 'board:post_delete' pk=posts.id %}" method="get" style="display:inline">
<!--        {% csrf_token %}-->
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>
<br>
<hr>
<br>
<a href="{% url 'board:index'%}"><h3>На главную страницу</h3></a>
</div>
{% endblock content %}