board/urls.py
from django.urls import path
from board.views import index, about, contacts, add_post, post_list_in_table, post_list, post_detail, post_edit, \
    post_delete

app_name = 'board'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('post/add', add_post, name='add_post'),
    path('post/table/', post_list_in_table, name='post_list_in_table'),
    path('post/', post_list, name='post_list'),
    path('posts/<slug:slug>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', post_edit, name='post_edit'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
]

my_board/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import root
from my_board import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "board.views.forbidden"
handler404 = "board.views.page_not_found"
handler500 = "board.views.server_error"

users/urls.py
from django.urls import path
from .views import register, log_in, log_out, user_detail, change_password, user_edit

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
    path('user/<int:pk>/edit/', user_edit, name='user_edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    city = models.CharField(max_length=100, verbose_name="Город")
    image = models.ImageField(upload_to="users/", null=True, verbose_name="Изображение")

users/forms.py
from django import forms
from django.contrib.auth import get_user_model

# Получение текущей модели пользователя
User = get_user_model()


# Создание формы регистрации пользователя
class UserRegistrationForm(forms.ModelForm):
    # Создание дополнительного поля пароля для повторного ввода при регистрации
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput)  # widget=forms.PasswordInput - скрытый ввод

    # def __init__(self, *args, **kwargs):
    #     author = kwargs.pop('author', None)
    #     super(UserRegistrationForm, self).__init__(*args, **kwargs)
    #     if author:
    #         self.fields['author'].initial = author
    #         self.fields['author'].disabled = True

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совпадают!')  # Если пароли не совпадают - генерируем исключение
        return cleaned_data['password2']

    class Meta:
        model = User  # Установка связи между model и User
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'phone', 'city')


class CustomPasswordChangeForm(forms.Form):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput)
    new_password_1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput)
    new_password_2 = forms.CharField(label="Повторите новый пароль", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password_1 = cleaned_data['new_password_1']
        new_password_2 = cleaned_data['new_password_2']
        old_password = cleaned_data['old_password']

        if new_password_1 and new_password_2 and new_password_1 != new_password_2:
            raise forms.ValidationError('Пароли не совпадают')

        if new_password_1 and new_password_2 and new_password_1 == new_password_2 and new_password_1 == old_password:
            raise forms.ValidationError("Пароли совпадают с текущим")

        return cleaned_data

users/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from django.contrib.auth import update_session_auth_hash
from my_board.settings import LOGIN_REDIRECT_URL
from .forms import UserRegistrationForm, CustomPasswordChangeForm
from .models import CustomUser

User = get_user_model()


def register(request):
    # если нажали кнопку регистрации (метод POST)
    if request.method == 'POST':
        # создаем объект с данными из запроса
        user_form = UserRegistrationForm(request.POST)
        # Валидация формы (правильность введенных данных)
        if user_form.is_valid():
            # Создание объекта с полями формы (без сохранения в БД)
            new_user = user_form.save(commit=False)
            # Хеширование пароля пользователя
            new_user.set_password(user_form.cleaned_data['password'])  # Хеширование пароля
            # Сохранение пользователя в БД
            new_user.save()  # по умолчанию commit=True
            context = {'title': 'Успешная регистрация', 'new_user': new_user}
            return render(request, template_name='users/register_done.html', context=context)

    # Если метод GET - отрисовка страницы регистрации
    user_form = UserRegistrationForm()
    context = {
        'title': 'Регистрация',
        'register_form': user_form
    }
    return render(request, template_name='users/register.html', context=context)


def log_in(request):
    # Создание формы аутентификации
    form = AuthenticationForm(request, request.POST)
    # Проверка формы
    if form.is_valid():
        # Получения логина и пароля из формы
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        # Аунтификация пользователя (проверка наличия пользователя и пароля)
        user = authenticate(username=username, password=password)
        if user is not None:
            # Авторизация пользователя (проверка прав доступа)
            login(request, user)
            # Получение дальнейшего маршрута после авторизации (next - путь, откуда пришел пользователь)
            url = request.GET.get('next', LOGIN_REDIRECT_URL)
            return redirect(url)
    context = {'form': form}
    return render(request, template_name='users/login.html', context=context)


@login_required
def log_out(request):
    logout(request)
    return redirect('board:index')


@login_required
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        raise PermissionDenied()

    context = {
        'user': user,
        'title': 'Информация о профиле'
    }

    return render(request, template_name='users/profile.html', context=context)


@login_required
def user_edit(request, pk):
    post = get_object_or_404(CustomUser, pk=pk)  # получить объект по ключу
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            return user_detail(request, pk=pk)

    else:
        form = UserRegistrationForm(instance=post)
    context = {
            'form': form,
            'title': 'Редактировать данные пользователя'
        }
    return render(request, template_name='users/user_edit.html', context=context)


def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.POST)

        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password_1']

            if request.user.check_password(old_password):
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user)
                return redirect('board:index')

            else:
                form.add_error('old_password', 'Старый пароль неверный')
                return redirect('users:change_password')

        return redirect('users:change_password')

    else:
        form = CustomPasswordChangeForm()
        context = {'title': 'Сменить пароль', 'form': form}
        return render(request, template_name='users/change_password.html', context=context)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="icon" href="{% static 'favicon/approval-icon.ico' %}"/>

</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'board:index' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'board:post_list' %}">Посты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Аккаунт
                    </a>
                    <ul class="dropdown-menu">
                        {% if not user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username }}</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                <li hidden class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/change_password.html
{% extends 'users/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
{{ form.non_field_error }}

    <div class="error-list">
        <p>Исправите следующие ошибки:</p>
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>

    <button type="submit">Сменить пароль</button>
</form>

{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}

<form class="row" method="post">
    {% csrf_token %}
    <!--  {{ form.as_p }}-->
    <div class="col-4 mx-5">
        <h2 class="col-12 mb-2 mx-3">Пожалуйста, войдите на сайт</h2>
        <div class="mb-4 form-control-lg">
            <i><label class="form-label">{{form.username.label}}: </label></i>
            <p>{{form.username}}</p>
            <i><label class="form-label">{{form.password.label}}:</label></i>
            <p>{{form.password}}</p>
        </div>
        <button type="submit" class="btn btn-primary col-4 mb-2 mx-3"><i class="bi bi-images mx-2"></i>Войти</button>
    </div>
</form>

{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block content %}

<h2>Информация о пользователе {{ user.username }}</h2>
<hr>
<div>Логин - {{ user.username }}</div>
<div>Имя - {{ user.first_name }}</div>
<div>Фамилия - {{ user.last_name }}</div>
<div>Эл.адрес - {{ user.email }}</div>
<div>Телефон - {{ user.phone }}</div>
<hr>
<div>Дата регистрации - {{ user.date_joined|date:'d-m-Y H:i'}}</div>

<a href="{% url 'users:user_edit' pk=user.id%}" class="btn btn-primary">Редактировать</a>

{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html '%}

{% block content %}

<h2>Регистрация пользователя</h2>
<form method="post">
    {% csrf_token %}
    {{ register_form }}

    <button type="submit"> Зарегистрироваться</button>
</form>

{% endblock content %}

users/templates/users/register_done.html
{% extends 'users/base.html '%}

{% block content %}

<h2> Пользователь {{ new_user.username }} успешно зарегистрирован </h2>

<p> Имя - {{ new_user.first_name }} </p>
<p> Фамилия - {{ new_user.last_name }} </p>
<p> Email - {{ new_user.email }} </p>
<p> Телефон - {{ new_user.phone }} </p>

{% endblock content %}

users/templates/users/user_edit.html
{% extends 'users/base.html' %}

{% block content %}

<!--<div class="container">-->
<!--    <form class="row" action="" method="post">-->
<!--        <legend><h2 class="col-12 mb-2 mx-3">{{title}}: <i>{{ user.username }}</i></h2></legend>-->
<!--        <label>{% csrf_token %}</label>-->
<!--        <label>{{ form.as_p }}</label>-->
<!--        <label>-->
<!--            <button type="submit">Редактировать</button>-->
<!--        </label>-->
<!--    </form>-->
<!--    <br>-->
<!--    <a href="{% url 'board:index'%}"><h3>На главную страницу</h3></a>-->
<!--</div>-->
<div class="container">
<form class="row" method="post">
    {% csrf_token %}
    <!--  {{ form.as_p }}-->
    <div class="col-6 mx-5">
        <h2 class="col-12 mb-2 mx-3">Редактировать данные пользователя <i>{{user.username}}</i></h2>
        <div class="mb-4 form-control-lg">
            <i><label class="form-label">{{form.first_name.label}}: </label></i>
            <p>{{form.first_name}}</p>
            <i><label class="form-label">{{form.last_name.label}}:</label></i>
            <p>{{form.last_name}}</p>
            <i><label class="form-label">{{form.phone.label}}:</label></i>
            <p>{{form.phone}}</p>
            <i><label class="form-label">{{form.email.label}}:</label></i>
            <p>{{form.email}}</p>
        </div>
        <button type="submit" class="btn btn-primary col-4 mb-2 mx-3"><i class="bi bi-images mx-2"></i>Редактировать</button>
    </div>
</form>
</div>


{% endblock content %}